//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcstokyucedag.Models.entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblmusteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblmusteriler()
        {
            this.tblsatis = new HashSet<tblsatis>();
        }
    
        public int musteriID { get; set; }

        [Required(ErrorMessage ="bu alani bos birakamazsiniz..")]
        [StringLength(50,ErrorMessage ="en fazla 50 karakter girebilirsiniz..")]
        public string musteriad { get; set; }


        [Required(ErrorMessage = "bu alani bos birakamazsiniz..")]
        [StringLength(50, ErrorMessage = "en fazla 50 karakter girebilirsiniz..")]
        public string musterisoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatis> tblsatis { get; set; }
    }
}
